token: adf4zs.ag09j43oy9082nvl
podnet: 10.244.0.0/16
kubernetes_version: 1.9*
phone_home_listen: 2223

k3s_version: v0.5.0-rc1
ansible_user: ansible
systemd_dir: /etc/systemd/system
master_ip: master1

